### ISSUE TITLE
beeswax templates fail to splice `@` forms

### ISSUE THREAD

**Issue by benknoble** [otherjoel/beeswax#12]
I've got a sample based on the second pollen tutorial: https://gist.github.com/benknoble/44a83076ab2c9091e4794274c9214ca8.

Notice the `'(@)` and blank lines where there should be data, as in the pollen version.

There are workarounds in some (but probably not all) cases, and it would be nice if this were fixed. (Also, when the body is a call to a tag function that produces a txexpr, it's not HTML-ified right, though I admit I don't have an example of that.)

**Comment by otherjoel** [comment]
Welp, that’s a problem! Thanks for the report.

**Comment by otherjoel** [comment]
Looks like there are multiple problems happening here.

1. Beeswax needs to do a little work to recognize and splice `@` forms when they appear directly in templates.
2. Beeswax isn’t initializing the `current-pagetree` parameter as Pollen does (which is why your `previous` and `next` expressions aren’t working).

**Comment by otherjoel** [comment]
> Also, when the body is a call to a tag function that produces a txexpr, it's not HTML-ified right, though I admit I don't have an example of that.

Can you explain further? Tagged x-expressions usually need to be converted by calling `->html`; this doesn’t happen automatically (in Pollen or Beeswax).

**Comment by benknoble** [comment]
> Can you explain further? Tagged x-expressions usually need to be converted by calling ->html; this doesn’t happen automatically (in Pollen or Beeswax).

I'll do some thinking and try to come up with an example, but I'm reasonably sure that with pollen a `txexpr?` result of `when/splice` is HTML-ified, and with Beeswax it's treated as you say. (In all other cases I agree with what you said.) I may be wrong, so I'll double check.

**Comment by otherjoel** [comment]
Thanks for your patience @benknoble  — it’s been a busy week! I don’t know how long it will take the package server to reflect these commits but once they do you should be able to `raco pkg update beeswax` and verify things now work as you expect.

**Comment by benknoble** [comment]
Thanks for working on this! Excited to test it out.

**Comment by otherjoel** [comment]
OK I see what’s going on. Any `define`s get moved to the top of the `apply-template` function that Beeswax wraps around the template. It so happens that the place they get put is outside the scope of the `parameterize` that sets the value of the `current-pagetree`. 

You can see this for yourself by removing the definitions of `prev-page` and `next-page` and just calling `(previous here)` and `(next here)` directly on those lines.

Obviously this is a bug, should be an easy fix. I've opened #16 to track this separately.

(Congrats on the new job!)

**Comment by otherjoel** [comment]
And fixed! The package server updated overnight. @benknoble let me know how it looks for you after a `raco pkg update beeswax` and (from inside the project folder) `raco pollen reset`.

**Comment by benknoble** [comment]
Will do!

**Comment by benknoble** [comment]
And, huge thanks for putting the time in on this ❤️

**Comment by benknoble** [comment]
Just for the record, I never came back around and tested this, but I haven't played with beeswax since then. I trust Joel that it's fixed, but I can't confirm—anyone interested in playing with the repro code should feel free to 😅
